version: "2"

plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx

exclude_patterns:
  - "**/__tests__/"
  - "**/__mocks__/"
  - "**/dist/"
  - "plugins/"
  - "static/"
  - ".yarn/"
  - ".github/"
  - ".vscode/"
  - "**/*.cjs"
  - ".pnp.*"
  - "jest.config.js"
  - "jest-preprocess.js"
  - "gatsby-config.js"
  - "gatsby-node.js"
  - "gatsby-browser.js"
  - "gatsby-ssr.js"
