version: "2"

plugins:
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 45
        typescript:
          mass_threshold: 45

exclude_patterns:
  - "**/__tests__/"
  - "**/__mocks__/"
  - "**/dist/"
  - "plugins/"
  - "static/"
  - ".yarn/"
  - ".github/"
  - ".vscode/"
  - "assets/"
  - "public/"
  - "**/*.cjs"
  - ".pnp.*"
  - "jest.config.js"
  - "jest-preprocess.js"
  - "gatsby-*.[jt]s"
  - "gatsby-*.[jt]sx"
