version: "2"

plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx

exclude_patterns:
  - "**/__tests__/"
  - "**/__mocks__/"
  - "**/dist/"
  - "plugins/"
  - "static/"
  - "ject.config.js"
  - "jest-preprocess.js"
  - "gatsby-config.js"
  - "gatsby-node.js"
