# Commands to start on workspace startup
tasks:
  - init: yarn install --immutable
    command: yarn run develop

# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    # Utils
    - streetsidesoftware.code-spell-checker
    - esbenp.prettier-vscode
    - vscode-icons-team.vscode-icons
    - wayou.vscode-todo-highlight
    - github.copilot
    - arcanis.vscode-zipfs
    # Language
    - dbaeumer.vscode-eslint
    - kavod-io.vscode-jest-test-adapter
    - mike-co.import-sorter
    - hbenl.vscode-test-explorer
