[package]
name = "periotrisjs_wasm"
description = "WASM part of Periotris.js"
version = "1.6.4"
authors = ["CSharperMantle <baorong2005@126.com>"]
homepage = "https://github.com/CSharperMantle/periotrisjs#readme"
repository = "https://github.com/CSharperMantle/periotrisjs/"
readme = "README.md"
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/wasm/lib.rs"

[dependencies]
wasm-bindgen = "0.2.63"

wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
opt-level = 3
lto = "thin"
