name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Set up dependencies
        run: |
          yarn install --immutable
      - name: Static type check
        run: |
          yarn run check
      - name: Build
        run: |
          yarn run ci-build-prefixed
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: public
