name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      - BUILD_ADD_PATH_PREFIX: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
      - name: Set up dependencies
        run: |
          yarn install --immutable
      - name: Static type check
        run: |
          yarn run check
      - name: Build
        run: |
          yarn run build --prefix-paths
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: public
