name: Gatsby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Set up dependencies
        run: |
          yarn global add gatsby-cli
          yarn install
      - name: Build
        run: |
          yarn run build

  test:
    needs: [build]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Set up dependencies
        run: |
          yarn global add jest
          yarn install
      - name: Test
        run: |
          yarn run test

  coverage:
    needs: [test]
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Set up dependencies
        run: |
          yarn global add jest
          yarn install
      - name: Coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn run coverage
