name: Gatsby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Set up dependencies
        run: |
          yarn install --immutable
      - name: Static type check
        run: |
          yarn run check
      - name: Build
        run: |
          yarn run build

  test:
    needs: [build]
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019
        node-version:
          - 14.x
          - 16.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Set up dependencies
        run: |
          yarn install --immutable
      - name: Test
        run: |
          yarn run test

  coverage:
    needs: [test]
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Set up dependencies
        run: |
          yarn install --immutable
      - name: Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn run coverage
