name: Gatsby

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019
        node-version:
          - 18.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Set up dependencies
        run: |
          yarn install --immutable
      - name: Build
        run: |
          yarn run build
      - name: Static type check
        run: |
          yarn run check
      - name: Test
        run: |
          yarn run test

  coverage:
    needs: [build]
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
      - name: Set up dependencies
        run: |
          yarn install --immutable
      - name: Coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn run coverage
